import type { Metadata } from "next";
import { Baloo_Da_2, Geist, Geist_Mono } from "next/font/google";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const balooDa2 = Baloo_Da_2({
  subsets: ["bengali"], // Specify the Bangla subset
  weight: ["400", "500", "600", "700", "800"], // Use desired font weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`antialiased ${balooDa2.className} bg-[#213555]`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
